project:
  type: website

website:
  title: "COVID-19 Affecting Factors and Hypothetical Analysis - Yifan Hu"
  sidebar:
    style: "docked"
    contents: 
      - href: index.qmd
        text: Introduction
      - href: Data-Sources.qmd
        text: Data Sources
      - href: Exploratory-Data-Analysis.qmd
        text: Exploratory Data Analysis
      - href: Statistical-Methods-Results.qmd
        text: Statistical Methods and Results
      - href: Conclusion.qmd
        text: Conclusion
      - href: Reference.qmd
        text: Reference
    tools:
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/hyf112/DSAN-5100-Project.git

format:
  html:
    theme: 
      - lux
      - custom.scss
    toc: true
    toc_float: 
      collapsed: false
      smooth_scroll: false
    code-fold: true
    code-copy: true
    code-tools: true
    code-overflow: wrap

editor: visual



